CREATE TABLE STUDENT
(
sid INT,
sname VARCHAR(25),
dob VARCHAR(12),
physics INT,
chemistry INT,
maths INT
);
DESCRIBE STUDENT;

INSERT INTO STUDENT(sid,sname,dob,physics,chemistry,maths) VALUES(1,'VAR','12-01-1999',81,85,80),
(2,'RINU','11-02-1999',60,75,86),
(3,'ABIN','13-03-1998',20,81,20),
(4,'ANUNADH','21-11-1996',70,88,86),
(5,'RINUS','30-09-1999',50,68,76);
SELECT * FROM STUDENT;
SELECT sid,sname FROM STUDENT  WHERE dob=(SELECT max(dob)from STUDENT);
SELECT * FROM STUDENT WHERE maths >=40 and (physics >=40 or chemistry >=40);
ALTER TABLE STUDENT ADD total int;
ALTER TABLE STUDENT ADD average float(10.3);
DESCRIBE STUDENT;
SELECT sname FROM STUDENT WHERE maths=(SELECT max(maths) FROM STUDENT);
SELECT sname FROM STUDENT WHERE chemistry=(SELECT min(chemistry) FROM STUDENT);
UPDATE STUDENT SET total=physics+chemistry+maths;
SELECT * FROM STUDENT;
UPDATE STUDENT SET average=total/3;
SELECT * FROM STUDENT;
SELECT * FROM STUDENT ORDER BY total DESC;
ALTER TABLE STUDENT RENAME COLUMN average TO avg_mark;
SELECT * FROM STUDENT;
SELECT sname FROM STUDENT WHERE avg_mark >(SELECT AVG(avg_mark) FROM STUDENT);
SELECT COUNT(*) FROM STUDENT WHERE AVG_MARK>(SELECT AVG(AVG_MARK) FROM STUDENT);